### ISSUE TITLE
[Bug] worker-loader cannot work with umi@3.4.0

### ISSUE THREAD

**Issue by Leemin0311** [umijs/umi#6247]
## What happens?

web worker cannot build successfully with umi@3.4.0.

worker-loader cannot find dependent module

Error: Cannot find module 'webpack/lib/webworker/WebWorkerTemplatePlugin'

## Mini Showcase Repository(REQUIRED)

https://github.com/Leemin0311/umi-worder-loader-bug

## How To Reproduce

**Steps to reproduce the behavior:** 
1. yarn
2. yarn start

**Expected behavior** 
1. build successfully

## Context

- **Umi Version**: 3.4.0
- **Node Version**: 14.7.0
- **Platform**: MacOS 11.2.2

**Comment by duan602728596** [comment]
如果是webpack5，试一试[@bbkkbkk/umi-webpack5-export](https://www.npmjs.com/package/@bbkkbkk/umi-webpack5-export)

**Comment by Dabada** [comment]
Webpack 5 no more needs worker-loader : [worker in webpack 5](https://webpack.js.org/guides/web-workers/#root)

But a have another problem with umi 3.4.0 : 
```
× Webpack
  Compiled with some errors in 45.68s

 ERROR  Failed to compile with 1 errors                                                                                                                                        9:07:46 AM
 error  in ./src/pages/exp/Camera/MediaStreamAdapter.ts

Module parse failed: Unexpected token (29:77)
File was processed with these loaders:
 * ./node_modules/@umijs/deps/compiled/babel-loader/index.js
You may need an additional loader to handle the result of these loaders.
|     // Worker Start
|
>     this.worker = new Worker(new URL('./MediaStreamAdapter.worker.js', import.meta.url));
|     this.worker.postMessage({
|       type: 'init',
```

**Comment by Dabada** [comment]
@sorrycc thank's for the new release.
Is it already available? I tried to upgrade to 3.4.1, unfortunately, yarn can't find it.

**Comment by sorrycc** [comment]
https://unpkg.fly.dev/browse/umi@3.4.1/
